default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: factual_development
  username: root
  password: root..
  host: localhost
  template: template0

test:
  <<: *default
  database: factual_test
  username: root
  password: root..
  template: template0
